--SET2 QUERY1--
-- a)Retrieve the average ratings of the movies for each year from 2010 to 2015.Consider the movies having Drama, Horror, Sci-Fi or Thriller as one of their genres.--

SELECT DISTINCT STARTYEAR YEAR,AVG(AVERAGERATING)  YEARLY_AVG
FROM sharmac.TITLE_RATINGS tr,
(SELECT TCONST,STARTYEAR,TITLETYPE FROM sharmac.TITLE_BASICS where GENRES IN
(Select DISTINCT GENRES
FROM sharmac.TITLE_BASICS
WHERE GENRES like'%Drama%' OR GENRES like'%Horror%' OR GENRES like'%Thriller%' OR GENRES like'%Sci-Fi%')) tb
WHERE tb.TCONST=tr.TCONST
AND tb.STARTYEAR>='2010' AND tb.STARTYEAR<='2015'
AND tb.TITLETYPE='movie'
GROUP BY tb.STARTYEAR
ORDER BY tb.STARTYEAR;


--SET2 QUERY2--
-- b) Retrieve the average ratings of the movies by genre for each year during 2010 and 2015 for each genre, Drama, Horror, Sci-Fi and Thriller.--
WITH part1
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Drama%'
AND tb.STARTYEAR='2010' AND tb.TITLETYPE='movie'),
part2
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Horror%'
AND tb.STARTYEAR='2010' AND tb.TITLETYPE='movie'),
part3
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Thriller%'
AND tb.STARTYEAR='2010' AND tb.TITLETYPE='movie'),
part4
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Sci-Fi%'
AND tb.STARTYEAR='2010' AND tb.TITLETYPE='movie'),
part5
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Drama%'
AND tb.STARTYEAR='2011' AND tb.TITLETYPE='movie'),
part6
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Horror%'
AND tb.STARTYEAR='2011' AND tb.TITLETYPE='movie'),
part7
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Thriller%'
AND tb.STARTYEAR='2011' AND tb.TITLETYPE='movie'),
part8
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Sci-Fi%'
AND tb.STARTYEAR='2011' AND tb.TITLETYPE='movie'),
part9
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Drama%'
AND tb.STARTYEAR='2012' AND tb.TITLETYPE='movie'),
part10
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Horror%'
AND tb.STARTYEAR='2012' AND tb.TITLETYPE='movie'),
part11
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Thriller%'
AND tb.STARTYEAR='2012' AND tb.TITLETYPE='movie'),
part12
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Sci-Fi%'
AND tb.STARTYEAR='2012' AND tb.TITLETYPE='movie'),
part13
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Drama%'
AND tb.STARTYEAR='2013' AND tb.TITLETYPE='movie'),
part14
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Horror%'
AND tb.STARTYEAR='2013' AND tb.TITLETYPE='movie'),
part15
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Thriller%'
AND tb.STARTYEAR='2013' AND tb.TITLETYPE='movie'),
part16
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Sci-Fi%'
AND tb.STARTYEAR='2013' AND tb.TITLETYPE='movie'),
part17
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Drama%'
AND tb.STARTYEAR='2014' AND tb.TITLETYPE='movie'),
part18
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Horror%'
AND tb.STARTYEAR='2014' AND tb.TITLETYPE='movie'),
part19
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Thriller%'
AND tb.STARTYEAR='2014' AND tb.TITLETYPE='movie'),
part20
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Sci-Fi%'
AND tb.STARTYEAR='2014' AND tb.TITLETYPE='movie'),
part21
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Drama%'
AND tb.STARTYEAR='2015' AND tb.TITLETYPE='movie'),
part22
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Horror%'
AND tb.STARTYEAR='2015' AND tb.TITLETYPE='movie'),
part23
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Thriller%'
AND tb.STARTYEAR='2015' AND tb.TITLETYPE='movie'),
part24
AS
(SELECT STARTYEAR, GENRES,AVERAGERATING FROM sharmac.TITLE_BASICS tb,
sharmac.TITLE_RATINGS tr WHERE tb.TCONST=tr.TCONST AND tb.GENRES like'%Sci-Fi%'
AND tb.STARTYEAR='2015' AND tb.TITLETYPE='movie')
SELECT STARTYEAR YEAR,'DRAMA' AS GENRES,AVG(AVERAGERATING) FROM part1 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Horror' AS GENRES,AVG(AVERAGERATING) FROM part2 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Thriller' AS GENRES,AVG(AVERAGERATING) FROM part3 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Sci-Fi' AS GENRES,AVG(AVERAGERATING) FROM part4 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'DRAMA' AS GENRES,AVG(AVERAGERATING) FROM part5 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Horror' AS GENRES,AVG(AVERAGERATING) FROM part6 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Thriller' AS GENRES,AVG(AVERAGERATING) FROM part7 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Sci-Fi' AS GENRES,AVG(AVERAGERATING) FROM part8 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'DRAMA' AS GENRES,AVG(AVERAGERATING) FROM part9 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Horror' AS GENRES,AVG(AVERAGERATING) FROM part10 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Thriller' AS GENRES,AVG(AVERAGERATING) FROM part11 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Sci-Fi' AS GENRES,AVG(AVERAGERATING) FROM part12 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'DRAMA' AS GENRES,AVG(AVERAGERATING) FROM part13 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Horror' AS GENRES,AVG(AVERAGERATING) FROM part14 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Thriller' AS GENRES,AVG(AVERAGERATING) FROM part15 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Sci-Fi' AS GENRES,AVG(AVERAGERATING) FROM part16 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'DRAMA' AS GENRES,AVG(AVERAGERATING) FROM part17 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Horror' AS GENRES,AVG(AVERAGERATING) FROM part18 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Thriller' AS GENRES,AVG(AVERAGERATING) FROM part19 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Sci-Fi' AS GENRES,AVG(AVERAGERATING) FROM part20 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'DRAMA' AS GENRES,AVG(AVERAGERATING) FROM part21 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Horror' AS GENRES,AVG(AVERAGERATING) FROM part22 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Thriller' AS GENRES,AVG(AVERAGERATING) FROM part23 GROUP BY STARTYEAR
UNION SELECT STARTYEAR YEAR,'Sci-Fi' AS GENRES,AVG(AVERAGERATING) FROM part24 GROUP BY STARTYEAR
;


